DEBUG 2016-09-30 21:09:30,992: 	 Executing command: 'status'
DEBUG 2016-09-30 21:09:30,992: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2016-09-30 21:09:31,002: 	 Checking credentials
DEBUG 2016-09-30 21:09:31,004: 	 Found proxy file /tmp/x509up_u79777
DEBUG 2016-09-30 21:09:31,005: 	 Getting proxy life time left
DEBUG 2016-09-30 21:09:31,914: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 86253

 error: 
 retcode : 0
DEBUG 2016-09-30 21:09:32,721: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -actimeleft
 output : 86252

 error: 
 retcode : 0
DEBUG 2016-09-30 21:09:32,721: 	 Proxy valid for 23:57:33 hours
ERROR 2016-09-30 21:09:32,754: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_QstarToQZm5000
ERROR 2016-09-30 21:09:32,754: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_QstarToQZm5000
DEBUG 2016-09-30 21:09:33,260: 	 Executing command: 'status'
DEBUG 2016-09-30 21:09:33,260: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2016-09-30 21:09:33,267: 	 Checking credentials
DEBUG 2016-09-30 21:09:33,268: 	 Found proxy file /tmp/x509up_u79777
DEBUG 2016-09-30 21:09:33,268: 	 Getting proxy life time left
DEBUG 2016-09-30 21:09:33,773: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 86251

 error: 
 retcode : 0
DEBUG 2016-09-30 21:09:34,280: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -actimeleft
 output : 86250

 error: 
 retcode : 0
DEBUG 2016-09-30 21:09:34,280: 	 Proxy valid for 23:57:31 hours
ERROR 2016-09-30 21:09:34,282: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_QstarToQZm7000
ERROR 2016-09-30 21:09:34,282: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_QstarToQZm7000
DEBUG 2016-09-30 21:09:34,710: 	 Executing command: 'status'
DEBUG 2016-09-30 21:09:34,710: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2016-09-30 21:09:34,716: 	 Checking credentials
DEBUG 2016-09-30 21:09:34,716: 	 Found proxy file /tmp/x509up_u79777
DEBUG 2016-09-30 21:09:34,716: 	 Getting proxy life time left
DEBUG 2016-09-30 21:09:35,221: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 86249

 error: 
 retcode : 0
DEBUG 2016-09-30 21:09:35,725: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -actimeleft
 output : 86249

 error: 
 retcode : 0
DEBUG 2016-09-30 21:09:35,725: 	 Proxy valid for 23:57:29 hours
ERROR 2016-09-30 21:09:35,726: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_dy_jetsToLL
ERROR 2016-09-30 21:09:35,726: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_dy_jetsToLL
DEBUG 2016-09-30 21:09:36,145: 	 Executing command: 'status'
DEBUG 2016-09-30 21:09:36,146: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2016-09-30 21:09:36,151: 	 Checking credentials
DEBUG 2016-09-30 21:09:36,151: 	 Found proxy file /tmp/x509up_u79777
DEBUG 2016-09-30 21:09:36,151: 	 Getting proxy life time left
DEBUG 2016-09-30 21:09:36,656: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 86248

 error: 
 retcode : 0
DEBUG 2016-09-30 21:09:37,261: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -actimeleft
 output : 86247

 error: 
 retcode : 0
DEBUG 2016-09-30 21:09:37,261: 	 Proxy valid for 23:57:28 hours
ERROR 2016-09-30 21:09:37,262: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_singleMuon_RunC25nsOct_MINIAOD_JSON1
ERROR 2016-09-30 21:09:37,262: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_singleMuon_RunC25nsOct_MINIAOD_JSON1
DEBUG 2016-09-30 21:09:37,697: 	 Executing command: 'status'
DEBUG 2016-09-30 21:09:37,697: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2016-09-30 21:09:37,704: 	 Checking credentials
DEBUG 2016-09-30 21:09:37,704: 	 Found proxy file /tmp/x509up_u79777
DEBUG 2016-09-30 21:09:37,704: 	 Getting proxy life time left
DEBUG 2016-09-30 21:09:38,210: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 86246

 error: 
 retcode : 0
DEBUG 2016-09-30 21:09:38,719: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -actimeleft
 output : 86246

 error: 
 retcode : 0
DEBUG 2016-09-30 21:09:38,720: 	 Proxy valid for 23:57:26 hours
ERROR 2016-09-30 21:09:38,721: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_singleMuon_RunDOct_v1_MINIAOD_JSON1
ERROR 2016-09-30 21:09:38,722: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_singleMuon_RunDOct_v1_MINIAOD_JSON1
DEBUG 2016-09-30 21:09:39,131: 	 Executing command: 'status'
DEBUG 2016-09-30 21:09:39,131: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2016-09-30 21:09:39,136: 	 Checking credentials
DEBUG 2016-09-30 21:09:39,136: 	 Found proxy file /tmp/x509up_u79777
DEBUG 2016-09-30 21:09:39,137: 	 Getting proxy life time left
DEBUG 2016-09-30 21:09:39,641: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 86245

 error: 
 retcode : 0
DEBUG 2016-09-30 21:09:40,146: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -actimeleft
 output : 86244

 error: 
 retcode : 0
DEBUG 2016-09-30 21:09:40,146: 	 Proxy valid for 23:57:25 hours
ERROR 2016-09-30 21:09:40,147: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_singleMuon_RunDPrompt_v4_MINIAOD_JSON1
ERROR 2016-09-30 21:09:40,148: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_singleMuon_RunDPrompt_v4_MINIAOD_JSON1
DEBUG 2016-09-30 21:09:40,565: 	 Executing command: 'status'
DEBUG 2016-09-30 21:09:40,565: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2016-09-30 21:09:40,570: 	 Checking credentials
DEBUG 2016-09-30 21:09:40,570: 	 Found proxy file /tmp/x509up_u79777
DEBUG 2016-09-30 21:09:40,570: 	 Getting proxy life time left
DEBUG 2016-09-30 21:09:41,175: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 86243

 error: 
 retcode : 0
DEBUG 2016-09-30 21:09:41,582: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -actimeleft
 output : 86243

 error: 
 retcode : 0
DEBUG 2016-09-30 21:09:41,582: 	 Proxy valid for 23:57:23 hours
ERROR 2016-09-30 21:09:41,583: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_ttJets
ERROR 2016-09-30 21:09:41,583: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_ttJets
DEBUG 2016-09-30 22:15:03,328: 	 Executing command: 'submit'
DEBUG 2016-09-30 22:15:03,329: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2016-09-30 22:15:03,340: 	 Checking credentials
DEBUG 2016-09-30 22:15:03,341: 	 Found proxy file /tmp/x509up_u79777
DEBUG 2016-09-30 22:15:03,341: 	 Getting proxy life time left
DEBUG 2016-09-30 22:15:03,949: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 604620

 error: 
 retcode : 0
DEBUG 2016-09-30 22:15:04,455: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -actimeleft
 output : 604619

 error: 
 retcode : 0
DEBUG 2016-09-30 22:15:04,455: 	 Proxy valid for 167:57:00 hours
INFO 2016-09-30 22:15:04,456: 	 Will use CRAB configuration file crab_auto_submit_QstarToQZm5000_JSON.py
DEBUG 2016-09-30 22:15:04,456: 	 Loading CRAB configuration file.
DEBUG 2016-09-30 22:15:04,458: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-09-30 22:15:04,459: 	 Working area '/afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_QstarToQZm5000' already exists 
Please change the requestName in the config file
ERROR 2016-09-30 22:15:04,459: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_QstarToQZm5000' already exists 
Please change the requestName in the config file
DEBUG 2016-09-30 22:15:04,877: 	 Executing command: 'submit'
DEBUG 2016-09-30 22:15:04,877: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2016-09-30 22:15:04,882: 	 Checking credentials
DEBUG 2016-09-30 22:15:04,883: 	 Found proxy file /tmp/x509up_u79777
DEBUG 2016-09-30 22:15:04,883: 	 Getting proxy life time left
DEBUG 2016-09-30 22:15:05,386: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 604618

 error: 
 retcode : 0
DEBUG 2016-09-30 22:15:05,890: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -actimeleft
 output : 604618

 error: 
 retcode : 0
DEBUG 2016-09-30 22:15:05,891: 	 Proxy valid for 167:56:58 hours
INFO 2016-09-30 22:15:05,891: 	 Will use CRAB configuration file crab_auto_submit_QstarToQZm7000_JSON.py
DEBUG 2016-09-30 22:15:05,892: 	 Loading CRAB configuration file.
DEBUG 2016-09-30 22:15:05,893: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-09-30 22:15:05,895: 	 Working area '/afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_QstarToQZm7000' already exists 
Please change the requestName in the config file
ERROR 2016-09-30 22:15:05,895: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_QstarToQZm7000' already exists 
Please change the requestName in the config file
DEBUG 2016-10-06 01:33:36,221: 	 Executing command: 'submit'
DEBUG 2016-10-06 01:33:36,223: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2016-10-06 01:33:36,255: 	 Checking credentials
DEBUG 2016-10-06 01:33:36,256: 	 Found proxy file /tmp/x509up_u79777
DEBUG 2016-10-06 01:33:36,256: 	 Getting proxy life time left
DEBUG 2016-10-06 01:33:36,868: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 604531

 error: 
 retcode : 0
DEBUG 2016-10-06 01:33:37,274: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -actimeleft
 output : 604530

 error: 
 retcode : 0
DEBUG 2016-10-06 01:33:37,274: 	 Proxy valid for 167:55:31 hours
INFO 2016-10-06 01:33:37,274: 	 Will use CRAB configuration file crab_auto_submit_dy_jetsToLL_JSON.py
DEBUG 2016-10-06 01:33:37,274: 	 Loading CRAB configuration file.
DEBUG 2016-10-06 01:33:37,278: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-10-06 01:33:37,295: 	 Working area '/afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_dy_jetsToLL' already exists 
Please change the requestName in the config file
ERROR 2016-10-06 01:33:37,295: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_dy_jetsToLL' already exists 
Please change the requestName in the config file
DEBUG 2016-10-07 03:11:36,643: 	 Executing command: 'submit'
DEBUG 2016-10-07 03:11:36,644: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2016-10-07 03:11:36,680: 	 Checking credentials
DEBUG 2016-10-07 03:11:36,680: 	 Found proxy file /tmp/x509up_u79777
DEBUG 2016-10-07 03:11:36,680: 	 Getting proxy life time left
DEBUG 2016-10-07 03:11:37,184: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 604789

 error: 
 retcode : 0
DEBUG 2016-10-07 03:11:37,587: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -actimeleft
 output : 604789

 error: 
 retcode : 0
DEBUG 2016-10-07 03:11:37,587: 	 Proxy valid for 167:59:49 hours
INFO 2016-10-07 03:11:37,588: 	 Will use CRAB configuration file crab_auto_submit_dy_jetsToLL_JSON.py
DEBUG 2016-10-07 03:11:37,588: 	 Loading CRAB configuration file.
DEBUG 2016-10-07 03:11:37,591: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-10-07 03:11:37,592: 	 Working area '/afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_dy_jetsToLL' already exists 
Please change the requestName in the config file
ERROR 2016-10-07 03:11:37,592: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_dy_jetsToLL' already exists 
Please change the requestName in the config file
DEBUG 2016-10-07 19:13:07,632: 	 Executing command: 'submit'
DEBUG 2016-10-07 19:13:07,640: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2016-10-07 19:13:07,702: 	 Checking credentials
DEBUG 2016-10-07 19:13:07,702: 	 Found proxy file /tmp/x509up_u79777
DEBUG 2016-10-07 19:13:07,702: 	 Getting proxy life time left
DEBUG 2016-10-07 19:13:08,409: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 604343

 error: 
 retcode : 0
DEBUG 2016-10-07 19:13:08,914: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -actimeleft
 output : 604343

 error: 
 retcode : 0
DEBUG 2016-10-07 19:13:08,915: 	 Proxy valid for 167:52:23 hours
INFO 2016-10-07 19:13:08,915: 	 Will use CRAB configuration file crab_auto_submit_QstarToQZm1000_JSON.py
DEBUG 2016-10-07 19:13:08,915: 	 Loading CRAB configuration file.
DEBUG 2016-10-07 19:13:08,922: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-10-07 19:13:08,922: 	 Working area '/afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_QstarToQZm1000' already exists 
Please change the requestName in the config file
ERROR 2016-10-07 19:13:08,922: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_QstarToQZm1000' already exists 
Please change the requestName in the config file
DEBUG 2016-10-07 19:13:09,543: 	 Executing command: 'submit'
DEBUG 2016-10-07 19:13:09,543: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2016-10-07 19:13:09,549: 	 Checking credentials
DEBUG 2016-10-07 19:13:09,549: 	 Found proxy file /tmp/x509up_u79777
DEBUG 2016-10-07 19:13:09,549: 	 Getting proxy life time left
DEBUG 2016-10-07 19:13:10,052: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 604342

 error: 
 retcode : 0
DEBUG 2016-10-07 19:13:10,559: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -actimeleft
 output : 604341

 error: 
 retcode : 0
DEBUG 2016-10-07 19:13:10,559: 	 Proxy valid for 167:52:22 hours
INFO 2016-10-07 19:13:10,560: 	 Will use CRAB configuration file crab_auto_submit_QstarToQZm2000_JSON.py
DEBUG 2016-10-07 19:13:10,560: 	 Loading CRAB configuration file.
DEBUG 2016-10-07 19:13:10,602: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-10-07 19:13:10,602: 	 Working area '/afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_QstarToQZm2000' already exists 
Please change the requestName in the config file
ERROR 2016-10-07 19:13:10,603: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_QstarToQZm2000' already exists 
Please change the requestName in the config file
DEBUG 2016-10-07 19:13:11,089: 	 Executing command: 'submit'
DEBUG 2016-10-07 19:13:11,089: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2016-10-07 19:13:11,095: 	 Checking credentials
DEBUG 2016-10-07 19:13:11,096: 	 Found proxy file /tmp/x509up_u79777
DEBUG 2016-10-07 19:13:11,096: 	 Getting proxy life time left
DEBUG 2016-10-07 19:13:11,703: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 604340

 error: 
 retcode : 0
DEBUG 2016-10-07 19:13:12,214: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -actimeleft
 output : 604339

 error: 
 retcode : 0
DEBUG 2016-10-07 19:13:12,214: 	 Proxy valid for 167:52:20 hours
INFO 2016-10-07 19:13:12,214: 	 Will use CRAB configuration file crab_auto_submit_QstarToQZm5000_JSON.py
DEBUG 2016-10-07 19:13:12,214: 	 Loading CRAB configuration file.
DEBUG 2016-10-07 19:13:12,222: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-10-07 19:13:12,223: 	 Working area '/afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_QstarToQZm5000' already exists 
Please change the requestName in the config file
ERROR 2016-10-07 19:13:12,224: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_2/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_QstarToQZm5000' already exists 
Please change the requestName in the config file
DEBUG 2016-10-07 19:13:12,665: 	 Executing command: 'submit'
DEBUG 2016-10-07 19:13:12,665: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2016-10-07 19:13:12,671: 	 Checking credentials
DEBUG 2016-10-07 19:13:12,671: 	 Found proxy file /tmp/x509up_u79777
DEBUG 2016-10-07 19:13:12,671: 	 Getting proxy life time left
DEBUG 2016-10-07 19:13:13,183: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 604338

 error: 
 retcode : 0
ERROR 2016-10-07 19:13:13,218: 	 Keyboard Interrupted
DEBUG 2016-10-30 15:26:41,591: 	 Executing command: 'submit'
DEBUG 2016-10-30 15:26:41,593: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2016-10-30 15:26:41,640: 	 Checking credentials
DEBUG 2016-10-30 15:26:41,641: 	 Found proxy file /tmp/x509up_u79777
DEBUG 2016-10-30 15:26:41,641: 	 Getting proxy life time left
DEBUG 2016-10-30 15:26:42,250: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 604736

 error: 
 retcode : 0
DEBUG 2016-10-30 15:26:42,758: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -actimeleft
 output : 604736

 error: 
 retcode : 0
DEBUG 2016-10-30 15:26:42,760: 	 Proxy valid for 167:58:56 hours
INFO 2016-10-30 15:26:42,760: 	 Will use CRAB configuration file crab_auto_submit_singleMuon_Run2016B_MINIAOD_JSON1.py
DEBUG 2016-10-30 15:26:42,760: 	 Loading CRAB configuration file.
DEBUG 2016-10-30 15:26:42,767: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-10-30 15:26:42,768: 	 Working area '/afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_12/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_singleMuon_Run2016B_MINIAOD_JSON1' already exists 
Please change the requestName in the config file
ERROR 2016-10-30 15:26:42,768: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_12/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_singleMuon_Run2016B_MINIAOD_JSON1' already exists 
Please change the requestName in the config file
DEBUG 2016-10-30 16:11:45,480: 	 Executing command: 'status'
DEBUG 2016-10-30 16:11:45,481: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2016-10-30 16:11:45,486: 	 Checking credentials
DEBUG 2016-10-30 16:11:45,486: 	 Proxy file /tmp/x509up_u79777 not found
DEBUG 2016-10-30 16:11:45,486: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2016-10-30 16:11:53,509: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 0
DEBUG 2016-10-30 16:11:53,913: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 86399

 error: 
 retcode : 0
DEBUG 2016-10-30 16:11:54,517: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -actimeleft
 output : 86398

 error: 
 retcode : 0
DEBUG 2016-10-30 16:11:54,920: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u79777 voms-proxy-info -fqan
 output : /cms/Role=NULL/Capability=NULL
/cms/uscms/Role=NULL/Capability=NULL

 error: 
 retcode : 0
DEBUG 2016-10-30 16:11:54,920: 	 Proxy created.
ERROR 2016-10-30 16:11:54,921: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_12/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_QstarToQZm1000
ERROR 2016-10-30 16:11:54,922: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_12/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_QstarToQZm1000
DEBUG 2016-10-30 16:11:55,270: 	 Executing command: 'status'
DEBUG 2016-10-30 16:11:55,270: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2016-10-30 16:11:55,274: 	 Checking credentials
DEBUG 2016-10-30 16:11:55,275: 	 Found proxy file /tmp/x509up_u79777
DEBUG 2016-10-30 16:11:55,275: 	 Getting proxy life time left
DEBUG 2016-10-30 16:11:55,680: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 86397

 error: 
 retcode : 0
DEBUG 2016-10-30 16:11:56,083: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -actimeleft
 output : 86396

 error: 
 retcode : 0
DEBUG 2016-10-30 16:11:56,083: 	 Proxy valid for 23:59:57 hours
ERROR 2016-10-30 16:11:56,084: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_12/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_QstarToQZm2000
ERROR 2016-10-30 16:11:56,085: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_12/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_QstarToQZm2000
DEBUG 2016-10-30 16:11:56,423: 	 Executing command: 'status'
DEBUG 2016-10-30 16:11:56,423: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2016-10-30 16:11:56,427: 	 Checking credentials
DEBUG 2016-10-30 16:11:56,427: 	 Found proxy file /tmp/x509up_u79777
DEBUG 2016-10-30 16:11:56,427: 	 Getting proxy life time left
DEBUG 2016-10-30 16:11:56,832: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 86396

 error: 
 retcode : 0
DEBUG 2016-10-30 16:11:57,236: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -actimeleft
 output : 86395

 error: 
 retcode : 0
DEBUG 2016-10-30 16:11:57,236: 	 Proxy valid for 23:59:56 hours
ERROR 2016-10-30 16:11:57,237: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_12/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_QstarToQZm5000
ERROR 2016-10-30 16:11:57,237: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_12/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_QstarToQZm5000
DEBUG 2016-10-30 16:11:57,575: 	 Executing command: 'status'
DEBUG 2016-10-30 16:11:57,575: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2016-10-30 16:11:57,579: 	 Checking credentials
DEBUG 2016-10-30 16:11:57,580: 	 Found proxy file /tmp/x509up_u79777
DEBUG 2016-10-30 16:11:57,580: 	 Getting proxy life time left
DEBUG 2016-10-30 16:11:57,983: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 86395

 error: 
 retcode : 0
DEBUG 2016-10-30 16:11:58,386: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -actimeleft
 output : 86394

 error: 
 retcode : 0
DEBUG 2016-10-30 16:11:58,387: 	 Proxy valid for 23:59:55 hours
ERROR 2016-10-30 16:11:58,388: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_12/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_singleMuon_Run2016B_MINIAOD_JSON1
ERROR 2016-10-30 16:11:58,388: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_12/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_singleMuon_Run2016B_MINIAOD_JSON1
DEBUG 2016-10-30 16:11:58,730: 	 Executing command: 'status'
DEBUG 2016-10-30 16:11:58,730: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2016-10-30 16:11:58,734: 	 Checking credentials
DEBUG 2016-10-30 16:11:58,734: 	 Found proxy file /tmp/x509up_u79777
DEBUG 2016-10-30 16:11:58,734: 	 Getting proxy life time left
DEBUG 2016-10-30 16:11:59,137: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 86393

 error: 
 retcode : 0
DEBUG 2016-10-30 16:11:59,540: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -actimeleft
 output : 86393

 error: 
 retcode : 0
DEBUG 2016-10-30 16:11:59,540: 	 Proxy valid for 23:59:53 hours
ERROR 2016-10-30 16:11:59,542: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_12/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_singleMuon_Run2016C_MINIAOD_JSON1
ERROR 2016-10-30 16:11:59,542: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_12/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_singleMuon_Run2016C_MINIAOD_JSON1
DEBUG 2016-10-30 16:11:59,872: 	 Executing command: 'status'
DEBUG 2016-10-30 16:11:59,872: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2016-10-30 16:11:59,876: 	 Checking credentials
DEBUG 2016-10-30 16:11:59,876: 	 Found proxy file /tmp/x509up_u79777
DEBUG 2016-10-30 16:11:59,876: 	 Getting proxy life time left
DEBUG 2016-10-30 16:12:00,380: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 86392

 error: 
 retcode : 0
DEBUG 2016-10-30 16:12:00,785: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -actimeleft
 output : 86392

 error: 
 retcode : 0
DEBUG 2016-10-30 16:12:00,785: 	 Proxy valid for 23:59:52 hours
ERROR 2016-10-30 16:12:00,786: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_12/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_singleMuon_Run2016D_MINIAOD_JSON1
ERROR 2016-10-30 16:12:00,786: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_12/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_singleMuon_Run2016D_MINIAOD_JSON1
DEBUG 2016-10-30 16:12:01,129: 	 Executing command: 'status'
DEBUG 2016-10-30 16:12:01,129: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2016-10-30 16:12:01,133: 	 Checking credentials
DEBUG 2016-10-30 16:12:01,133: 	 Found proxy file /tmp/x509up_u79777
DEBUG 2016-10-30 16:12:01,133: 	 Getting proxy life time left
DEBUG 2016-10-30 16:12:01,536: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 86391

 error: 
 retcode : 0
DEBUG 2016-10-30 16:12:01,940: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -actimeleft
 output : 86391

 error: 
 retcode : 0
DEBUG 2016-10-30 16:12:01,941: 	 Proxy valid for 23:59:51 hours
ERROR 2016-10-30 16:12:01,942: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_12/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_singleMuon_Run2016E_MINIAOD_JSON1
ERROR 2016-10-30 16:12:01,942: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_12/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_singleMuon_Run2016E_MINIAOD_JSON1
DEBUG 2016-10-30 16:12:02,298: 	 Executing command: 'status'
DEBUG 2016-10-30 16:12:02,299: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2016-10-30 16:12:02,306: 	 Checking credentials
DEBUG 2016-10-30 16:12:02,307: 	 Found proxy file /tmp/x509up_u79777
DEBUG 2016-10-30 16:12:02,307: 	 Getting proxy life time left
DEBUG 2016-10-30 16:12:02,812: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 86390

 error: 
 retcode : 0
DEBUG 2016-10-30 16:12:03,216: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -actimeleft
 output : 86389

 error: 
 retcode : 0
DEBUG 2016-10-30 16:12:03,216: 	 Proxy valid for 23:59:50 hours
ERROR 2016-10-30 16:12:03,217: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_12/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_singleMuon_Run2016F_MINIAOD_JSON1
ERROR 2016-10-30 16:12:03,217: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/b/bregnery/public/BoostedZStudies/CMSSW_8_0_12/src/UfHMuMuCode/UFDiMuonsAnalyzer/test/crab_projects/crab_singleMuon_Run2016F_MINIAOD_JSON1
